version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:80"
    networks:
      - tp
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    networks:
      - tp

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - "./gens:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    networks:
      - tp

networks:
  tp:
    name: "maria"